-- ALTER TABLE -- 

-- ADCIONANDO AS FOREIGN KEYS --

USE editora;

-- TABELA EDITORA --
ALTER TABLE editora 
ADD FOREIGN KEY (Id_Endereco) REFERENCES enderecos (Id_Endereco) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (Id_Departamentos) REFERENCES departamentos (Id_Departamento) ON DELETE CASCADE ON UPDATE CASCADE;

-- TABELA DEPARTAMENTOS --
ALTER TABLE departamentos 
ADD FOREIGN KEY (Id_Gerente) REFERENCES gerentes (Id_Gerente) ON DELETE CASCADE ON UPDATE CASCADE;

-- TABELA FUNCIONARIOS_DEPARTAMENTOS --
ALTER TABLE funcionarios_departamentos
ADD FOREIGN KEY (Id_Departamento) REFERENCES departamentos (Id_Departamento) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (Id_Gerente) REFERENCES gerentes (Id_Gerente) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (CPF_Pessoas_Funcionarios) REFERENCES pessoas (CPF_Pessoas) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (ocupacao_CBO) REFERENCES ocupacao (CBO) ON DELETE CASCADE ON UPDATE CASCADE;

-- TABELA FUNCIONARIOS --
ALTER TABLE funcionarios 
ADD FOREIGN KEY (CPF_Pessoas_Funcionarios) REFERENCES pessoas (CPF_Pessoas) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (Id_Enderecos) REFERENCES enderecos (Id_Endereco) ON DELETE CASCADE ON UPDATE CASCADE;

-- TABELA GERENTES --
ALTER TABLE gerentes 
ADD FOREIGN KEY (CPF_Pessoas_Funcionarios) REFERENCES funcionarios (CPF_Pessoas_Funcionarios) ON DELETE CASCADE ON UPDATE CASCADE;

-- TABELA AUTORES --
ALTER TABLE autores 
ADD FOREIGN KEY (CPF_Pessoas_Autores) REFERENCES pessoas (CPF_Pessoas) ON DELETE CASCADE ON UPDATE CASCADE;

-- TABELA LIVRARIAS --
ALTER TABLE livrarias 
ADD FOREIGN KEY (Id_Departamento) REFERENCES departamentos (Id_Departamento) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (Id_Endereco) REFERENCES enderecos (Id_Endereco) ON DELETE CASCADE ON UPDATE CASCADE;

-- TABELA EXEMPLARES --
ALTER TABLE exemplares 
ADD FOREIGN KEY (CNPJ_Editora) REFERENCES editora (CNPJ_Editora) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (Id_Endereco) REFERENCES enderecos (Id_Endereco) ON DELETE CASCADE ON UPDATE CASCADE;

-- TABELA EXEMPLARES AUTORES --
ALTER TABLE exemplares_autores
ADD FOREIGN KEY (CPF_Pessoas_Autores) REFERENCES pessoas (CPF_Pessoas) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (Id_Exemplar) REFERENCES exemplares (Id_Exemplar) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (CNPJ_Editora) REFERENCES editora (CNPJ_Editora) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (Id_Endereco) REFERENCES enderecos (Id_Endereco) ON DELETE CASCADE ON UPDATE CASCADE;


